import networkx as nx
import matplotlib.pyplot as plt

G = nx.Graph()

G.add_node("C")
G.add_node("E")
G.add_node("Ratfor")
G.add_node("C shell")
G.add_node("C++")
G.add_node("AMPL")
G.add_node("Objective-C")
G.add_node("C*")
G.add_node("Perl")
G.add_node("Java")
G.add_node("S-Lang")
G.add_node("SAC")
G.add_node("Alef")
G.add_node("Limbo")
G.add_node("PHP")
G.add_node("ECMAscript")
G.add_node("C--")
G.add_node("C#")
G.add_node("Ch")
G.add_node("D")
G.add_node("eC")
G.add_node("Cyclone")
G.add_node("LSL")
G.add_node("Squirrel")
G.add_node("Go")
G.add_node("OpenCL C")
G.add_node("C0")
G.add_node("Swift")
G.add_node("AWK")
G.add_node("BitC")
G.add_node("LPC")
G.add_node("PYKE")
G.add_node("Speed7")
G.add_node("Processing")
G.add_node("Split-C")
G.add_node("Unifield Parallel C")
G.add_node("Cilk")
G.add_node("Chapel")
G.add_node("Fortress")
G.add_node("Agora")
G.add_node("Falcon")
G.add_node("BCPL")
G.add_node("B")
G.add_node("Nim")
G.add_node("Nemerle")
G.add_node("ApeScript")
G.add_node("Amiga E")
G.add_node("Lite-C")
G.add_node("Newsqueak")
G.add_node("NXC")
G.add_node("NQC")
G.add_node("OAK")
G.add_node("PROMAL")
G.add_node("Handel-C")
G.add_node("Dart")
G.add_node("CINT")
G.add_node("Cg")
G.add_node("nesC")
G.add_node("R")
G.add_node("Hack")
G.add_node("Charm")
G.add_node("Claire")
G.add_node("Noop")
G.add_node("Neko")
G.add_node("Axum")
G.add_node("Umple")
G.add_node("TOM")
G.add_node("Telescript")
G.add_node("Fantom")

i = G.node("E")
node_sizes = [150]
for i in G.nodes:
    G.add_edge(i, "C")
    node_sizes.append(0)

nx.draw_networkx(G, node_size = node_sizes, node_color = 'w', style = 'dotted', font_size = 8)
plt.show()
